# permissions for end users to view scalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: schedule-pod-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-viewer-role
rules:
- apiGroups:
  - api.snappcloud.io
  resources:
  - scalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.snappcloud.io
  resources:
  - scalers/status
  verbs:
  - get
